### ISSUE TITLE
Decide APIs for the project

### ISSUE THREAD

**Issue by ShreyBhatt** [SJSU272Lab/Fall16-Team27#6]

**Comment by parthmupadhyay** [comment]
@parvezpatel30 @appsmehta @ShreyBhatt 
Created new branch API-fitbit
Separated Fitbit library and created api's in home.js
Kindly use the project in mentioned branch for further development.

**Comment by parvezpatel30** [comment]
@parthmupadhyay Hey Parth, we should keep one unified branch for the final working code.
Why don't you try and merge the code with the master branch?

**Comment by parthmupadhyay** [comment]
@parvezpatel30 
Master branch project structure is not correct.
Fitbit-api.js file is kept outside.
All api's defined within app.js which made understanding flow within app.js difficult

I created new project with express4 with proper structure.
API's defined within routes folder.
It will be better if you guys develop UI and angular part with this new project.

**Comment by parvezpatel30** [comment]
@parthmupadhyay I understand. But Since the structure you have changed is the one we will be using going forward, it should be in the master branch. 

I have merged your code with master branch manually, please take latest code from master branch and check if everything is working fine.

Thanks :)

**Comment by ShreyBhatt** [comment]
Changed OAuth 2.0 Application Type  to personal to get intraday hertrate data

reference: https://community.fitbit.com/t5/Web-API/Intraday-data-now-immediately-available-to-personal-apps/m-p/1014524
